### ISSUE TITLE
Channels 2 - ROUTING key deprecation

### ISSUE THREAD

**Issue by bctrainers** [ScanOC/trunk-player#158]
Decided to spool up a new instance of TrunkPlayer today, and came across a new error...

```python
2022-09-20 10:49:14,934 ERROR    Exception inside application: ROUTING key found for default - this is no longer needed in Channels 2.
Traceback (most recent call last):
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/consumer.py", line 44, in __call__
    self.channel_layer = get_channel_layer(self.channel_layer_alias)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/layers.py", line 359, in get_channel_layer
    return channel_layers[alias]
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/layers.py", line 78, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/layers.py", line 44, in make_backend
    return self._make_backend(name, config)
  File "/home/radio/trunk-player/env/lib/python3.9/site-packages/channels/layers.py", line 59, in _make_backend
    raise InvalidChannelLayerError(
channels.exceptions.InvalidChannelLayerError: ROUTING key found for default - this is no longer needed in Channels 2.
```

**Comment by bctrainers** [comment]
May be operator error on my part, lazy copy-pasting on config files. 

Fix for this is changing CHANNEL_LAYERS to the following in settings.py or settings_local.py. Ensuring the `redis://IP.IP.IP.IP:port/db` is set correctly. 

```python
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://10.20.30.40:6379/9')],
            "prefix": "trunkplayer:",
            "channel_capacity": {
                "http.request": 200,
                "http.response!*": 10,
            },
            "capacity": 255,
        },
    },
}
```
