### ISSUE TITLE
--web_dir Not Working JSON w/ multiple folders not found

### ISSUE THREAD

**Issue by MaxwellDPS** [ScanOC/trunk-player#51]
Hey,

Trying to get setup again...
I am using this script with trunk recorder Notice **NESR/2018/7/9/** 
```
#! /bin/bash
REMOTE_USER_NAME="radio"
REMOTE_SERVER="172.16.0.29"
echo "Encoding: $1"
filename="$1"
basename="${filename%.*}"
filename_only=$(basename $basename)
json="$basename.json"
AACencoded="$basename.m4a"                                                                #NEW
web_dir=$(dirname $filename | cut -d/ -f4-)"/"  #produces NESR/2018/7/9/ 
system=0 # Change this for each system

# Hack the JSON to add play length and source
len=$(soxi -D $filename)

head -n-2 $json > $json.new
echo "\"play_length\": $len," >> $json.new
echo "\"source\": 0," >> $json.new
tail -n2 $json >> $json.new
mv $json.new $json


ffmpeg -i $filename -c:a libfdk_aac -profile:a aac_he -b:a 32k -ar 48k $AACencoded

ssh -q $REMOTE_USER_NAME@$REMOTE_SERVER "cd /home/radio/trunk-player; . env/bin/activate; ./manage.py add_transmission --m4a --web_url=$web_dir --system=$system $basename"
echo "[+] UPLOADED AND ADDED"
rm -f $filename
```
Trunk recorder output 

```
[2018-07-09 16:06:23.962240] (info)     - Starting P25 Recorder Num [0] TG: 3075        Freq: 1.554225e+08      TDMA: false     Slot: 0
[2018-07-09 16:06:23.963387] (info)   [NESR]    TG: 3075        Freq: 1.554225e+08      Starting Recorder on Src: rtl=0
[2018-07-09 16:06:40.010503] (info)   [NESR]    TG: 3075        Freq: 1.554225e+08      Ending Recorded Call - Last Update: 4s  Call Elapsed: 11
[2018-07-09 16:06:40.028903] (info)     - Stopping P25 Recorder Num [0] TG: 3075        Freq: 1.554225e+08      TDMA: false     Slot: 0
[2018-07-09 16:06:40.047753] (info)   Running upload script: ./trans.sh /mnt/radio/NESR/2018/7/9/3075-1531170383_1.55422e+08.wav &
Encoding: /mnt/radio/NESR/2018/7/9/3075-1531170383_1.55422e+08.wav
./trans.sh: line 14: soxi: command not found
ffmpeg version N-91439-gc71e1e6 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --pkg-config-flags=--static --bindir=/home/max/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-nonfree
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 21.104 / 58. 21.104
  libavformat    58. 17.101 / 58. 17.101
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 25.100 /  7. 25.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from '/mnt/radio/NESR/2018/7/9/3075-1531170383_1.55422e+08.wav':
  Duration: 00:00:05.94, bitrate: 128 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 8000 Hz, mono, s16, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, ipod, to '/mnt/radio/NESR/2018/7/9/3075-1531170383_1.55422e+08.m4a':
  Metadata:
    encoder         : Lavf58.17.101
    Stream #0:0: Audio: aac (libfdk_aac) (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, mono, s16, 32 kb/s
    Metadata:
      encoder         : Lavc58.21.104 libfdk_aac
size=      25kB time=00:00:05.95 bitrate=  34.6kbits/s speed=51.6x
video:0kB audio:24kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 5.612454%
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/radio/trunk-player/radio/management/commands/add_transmission.py", line 60, in handle
    add_new_trans(options)
  File "/home/radio/trunk-player/radio/management/commands/add_transmission.py", line 134, in add_new_trans
    with open(json_file) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'audio_files/3075-1531170383_1.55422e+08.json'
[+] UPLOADED AND ADDED

```
its giving **FileNotFoundError: [Errno 2] No such file or directory: 'audio_files/3075-1531170383_1.55422e+08.json'**

however when I try running the import manually I get the same 

```
(Trunk Player)radio@Radio:~/trunk-player$ ./manage.py add_transmission --web_url=NESR/2018/7/8 --m4a 3071-1531096258_1.5278e+08
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/radio/trunk-player/env/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/radio/trunk-player/radio/management/commands/add_transmission.py", line 60, in handle
    add_new_trans(options)
  File "/home/radio/trunk-player/radio/management/commands/add_transmission.py", line 134, in add_new_trans
    with open(json_file) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'audio_files/3071-1531096258_1.5278e+08.json'

```
So im calling this however its ignoring the web_url arg... Did I miss something
**./manage.py add_transmission --web_url=NESR/2018/7/8 --m4a 3071-1531096258_1.5278e+08**

**Comment by kcwebby** [comment]
Hi there,

I might be wrong, but I think web_dir is just passed to the database in the
instance that you store the file in a different path on the web end of
things than the local server (file side).   I believe you can fix the error
by calling out the file directly by path later in your command.

*./manage.py add_transmission --web_url=NESR/2018/7/8 --m4a
NESR/2018/7/8/3071-1531096258_1.5278e+08*

On Mon, Jul 9, 2018 at 4:30 PM, Maxwell Watermolen <notifications@github.com

**Comment by dreinhold** [comment]
The --web_url is just about the m4a/mp3. The system still expects the .json to be just in audio_files/
